const SECOND_MS = 1000;
const MINUTE_MS = 60 * SECOND_MS;
const HOUR_MS = 60 * MINUTE_MS;
const DAY_MS = 24 * HOUR_MS;
const WEEK_MS = 7 * DAY_MS;

const MINUTE = 60;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;
const WEEK = 7 * DAY;

export const TIME_MS = {
  ONE_SECOND: SECOND_MS,
  TWO_SECONDS: 2 * SECOND_MS,
  THREE_SECONDS: 3 * SECOND_MS,
  FIVE_SECONDS: 5 * SECOND_MS,
  TEN_SECONDS: 10 * SECOND_MS,
  THIRTY_SECONDS: 30 * SECOND_MS,

  ONE_MINUTE: MINUTE_MS,
  FIVE_MINUTES: 5 * MINUTE_MS,
  FIFTEEN_MINUTES: 15 * MINUTE_MS,

  ONE_HOUR: HOUR_MS,
  ONE_DAY: DAY_MS,
  THREE_DAYS: 3 * DAY_MS,
  ONE_WEEK: WEEK_MS,
} as const;

export const TIME_SECONDS = {
  ONE_MINUTE: MINUTE,
  FIVE_MINUTES: 5 * MINUTE,
  TEN_MINUTES: 10 * MINUTE,
  FIFTEEN_MINUTES: 15 * MINUTE,

  ONE_HOUR: HOUR,
  ONE_DAY: DAY,
  ONE_WEEK: WEEK,
} as const;
