const SECOND = 1000;
const MINUTE = 60 * SECOND;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;

export const TIME_MS = {
  ONE_SECOND: SECOND,
  TWO_SECONDS: 2 * SECOND,
  TEN_SECONDS: 10 * SECOND,
  THIRTY_SECONDS: 30 * SECOND,
  ONE_MINUTE: 60 * SECOND,
  FIVE_MINUTES: 5 * MINUTE,
  FIFTEEN_MINUTES: 15 * MINUTE,
  ONE_HOUR: HOUR,
  ONE_DAY: DAY,
  THREE_DAYS: 3 * DAY,
  SEVEN_DAYS: 7 * DAY,
} as const;

export const TIME_SECONDS = {
  ONE_MINUTE: 60,
  FIVE_MINUTES: 5 * 60,
  TEN_MINUTES: 10 * 60,
  FIFTEEN_MINUTES: 15 * 60,
  ONE_HOUR: 60 * 60,
  SEVEN_DAYS: 7 * 24 * 60 * 60,
} as const;
